[package]
name = "app"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "bynrust26"
path = "src/main.rs"

[features]
default = ["sqlite"]
sqlite = ["sea-orm/sqlx-sqlite", "migration/sqlite"]
postgres = ["sea-orm/sqlx-postgres", "migration/postgres"]
mysql = ["sea-orm/sqlx-mysql", "migration/mysql"]

[dependencies]
migration.workspace = true
axum.workspace = true
tokio.workspace = true
tower-http.workspace = true
sea-orm.workspace = true
config.workspace = true
serde.workspace = true
serde_json.workspace = true
dotenvy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
jsonwebtoken.workspace = true
redis.workspace = true
argon2.workspace = true
rand_core.workspace = true
uuid.workspace = true
chrono.workspace = true
md5.workspace = true

[dev-dependencies]
tower.workspace = true
